from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login_page, name='login_page'),
    path('register/', views.register_page, name='register_page'),
    path('logout/', views.logout_page, name='logout_page'),
    path('', views.index, name='index'),
    path('help/', views.help_page, name='help_page'),
    path('admin-center/', views.admin_center_page, name='admin_center_page'),
    path('admin-center/promote/<int:user_id>/', views.promote_user_admin, name='promote_user_admin'),
    path('admin-center/users/create/', views.admin_create_user, name='admin_create_user'),
    path('admin-center/users/<int:user_id>/update/', views.admin_update_user, name='admin_update_user'),
    path('admin-center/cards/<int:card_id>/update/', views.admin_update_card, name='admin_update_card'),
    path('admin-center/cards/<int:card_id>/delete/', views.admin_delete_card, name='admin_delete_card'),
    path('dashboard/', views.dashboard_page, name='dashboard_page'),
    path('profile/', views.profile_page, name='profile_page'),
    path('settings/', views.settings_page, name='settings_page'),
    path('settings/theme/', views.set_theme_mode, name='set_theme_mode'),
    path('reports/', views.reports_page, name='reports_page'),
    path('collections/', views.collections_page, name='collections_page'),
    path('friends/', views.friends_page, name='friends_page'),
    path('chat/', views.chat_hub_page, name='chat_hub_page'),
    path('ai-helper/', views.ai_helper_page, name='ai_helper_page'),
    path('ai-helper/reply/', views.ai_helper_reply, name='ai_helper_reply'),
    path('chat/<int:friend_id>/', views.chat_page, name='chat_page'),
    path('chat/messages/<int:message_id>/delete/', views.delete_chat_message, name='delete_chat_message'),
    path('favorites/', views.favorites_page, name='favorites_page'),
    path('friends/add/', views.add_friend, name='add_friend'),
    path('friends/<int:friend_id>/remove/', views.remove_friend, name='remove_friend'),
    path('cards/<int:card_id>/share/', views.share_card_to_chat, name='share_card_to_chat'),
    path('cards/add/', views.add_card, name='add_card'),
    path('cards/<int:card_id>/', views.card_detail, name='card_detail'),
    path('cards/<int:card_id>/edit/', views.edit_card, name='edit_card'),
    path('cards/<int:card_id>/delete/', views.delete_card, name='delete_card'),
    path('cards/export/', views.export_cards_json, name='export_cards_json'),
    path('cards/import/', views.import_cards_json, name='import_cards_json'),
    path('sidebar/', views.sidebar_items_page, name='sidebar_items_page'),
    path('sidebar/item/<int:item_id>/', views.sidebar_item_detail, name='sidebar_item_detail'),
    path('sidebar/add/', views.sidebar_item_add, name='sidebar_item_add'),
    path('sidebar/<int:item_id>/update/', views.sidebar_item_update, name='sidebar_item_update'),
    path('sidebar/<int:item_id>/delete/', views.sidebar_item_delete, name='sidebar_item_delete'),
]
